#!/bin/bash
#
# git-dude-exherbo - Git commit notifier used in #exherbo
# https://github.com/somasis/git-dude-exherbo
#
# Copyright (C) 2011-2015 Marcin Kulik <http://ku1ik.com/>
# Copyright (C) 2015 Kylie McClain <somasissounds@gmail.com>
#
# Other contributions from:
#   Alexander von Gluck IV <https://github.com/kallisti5>
#   Anders Olsson <https://github.com/logaritmisk>
#   Daniel Heath <https://github.com/DanielHeath>
#   Eric Jiang <https://github.com/erjiang>
#   Henrik Holmboe <https://github.com/holmboe>
#   Josh Dick <https://github.com/joshdick>
#   Lochlan Bunn <https://github.com/loklaan>
#   Michael Wolf <https://github.com/maw>
#   Rogerio Prado de Jesus <https://github.com/rogeriopradoj>
#   Stefano Ongeri <https://github.com/stelinx>
#   Łukasz Korecki <https://github.com/lukaszkorecki>
#
# Distributed under the GNU General Public License, version 3.0.
#

set -o errexit

dir=$(git config --global dude.default-dir || true)
dir=${dir:-~/.git-dude}

max_jobs=$(git config --global dude.max-jobs || true)
max_jobs=${max_jobs:-10}

notify_command=$(git config --global dude.notify-command || true)

app_name=$(basename $0)

set -e

export LC_ALL=C # make sure git talks english

normal=$'\u000F'
bold=$'\u0002'
underline=$'\u001F'
blue=$'\u0003'"02"
green=$'\u0003'"03"
purple=$'\u0003'"06"
orange=$'\u0003'"07"
lightblue=$'\u0003'"12"
pink=$'\u0003'"13"

set_category() {
    echo "unofficial"
}

interval() {
    interval=60
}

dudenotify() {
    local TITLE="$repo_name/$branch"
    local TYPE="$1"
    local DESC="$@"
    echo "${bold}$TITLE${normal}: $ACTION - $@"
    sleep 2s
}

get_url() { # get_url <type> <remote> <hash/branch name>
    type="$1"
    if [[ "$type" == "commit" ]];then
        case "$2" in
            *git.exherbo.org*)
                echo " - $2/commit/?id=$3"
                ;;
            *gitlab.com*)
                local get_url=$(echo "$2" | sed 's/\.git//')
                echo " - $2/commit/$3"
                ;;
            *github.com*)
                local get_url=$(echo "$2" | sed 's/\.git//')
                echo " - $get_url/commit/$3"
                ;;
        esac
    elif [[ "$type" == "branch" ]];then
        case "$2" in
            *git.exherbo.org*)
                echo " - $2/log/?h=$3"
                ;;
            *gitlab.com*)
                local get_url=$(echo "$2" | sed 's/\.git//')
                echo " - $get_url/commits/$3"
                ;;
            *github.com*)
                local get_url=$(echo "$2" | sed 's/\.git//')
                echo " - $get_url/commits/$3"
                ;;
        esac
    elif [[ "$type" == "tag" ]];then
        case "$2" in
            *git.exherbo.org*)
                echo " - $2/tag/?id=$3"
                ;;
            *gitlab.com*)
                local get_url=$(echo "$2" | sed 's/\.git//')
                echo " - $get_url/commits/$3"
                ;;
            *github.com*)
                local get_url=$(echo "$2" | sed 's/\.git//')
                echo " - $get_url/commits/$3"
                ;;
        esac
    fi
}

say() {
    local msg="$@"
    local length=$(echo "$msg" | wc -c)
    [[ "$length" -gt 394 ]] && local msg=$(echo "$msg" | cut -c-394)
    sleep 3s
    echo "$msg"
}

if [[ -d "$1" ]];then
    cd "$1"
else
    cd "$dir"
fi

screensaver() { false; }

#say "started at $(date +'%X %x')."

dir="$PWD"

while true; do
    if ! screensaver; then
        for dir_name in *; do
            jobs=$(jobs | grep ' git' | wc -l)
                {
                    if [[ -d "$dir_name" && $(cd "$dir_name"; git rev-parse --git-dir 2>/dev/null) ]]; then
                        if [[ $(cd "$dir_name"; git config dude.ignore) == true ]]; then
                            continue
                        fi

                        repo_name=$(basename "$dir_name" .git)
                        cd "$dir_name"

                        remote=$(git config dude.remote || true)
                        changes=$(yes '' | git fetch -v $(git config dude.fargs) $remote 2>&1 | grep -F -- '->' | sed 's/^ [+*=!-] //')
                        url=$(git config --get remote.origin.url)
                        category=$(set_category)

                        while read -r line; do
                            #printf "%s:\t%s\n" "$repo_name" "$line" >&2
                            case "$line" in
                                *..*)
                                    commit_range=$(echo "$line" | awk '{ print $1 }')
                                    branch_name=$(echo "$line" | awk '{ print $2 }')
                                    OLDIFS="$IFS"
                                    IFS=$'\n'
                                    { git log $commit_range --pretty=format:"${category}|${repo_name}:${branch_name}|%h|%aE|%s" | sed '1!G;h;$!d'; echo; } | grep -Ev '^[[:space:]]*$' | \
                                        while read commit_line;do
                                            category=$(echo "$commit_line" | cut -d'|' -f1)
                                            location=$(echo "$commit_line" | cut -d'|' -f2)
                                            hash=$(echo "$commit_line" | cut -d'|' -f3)
                                            author=$(echo "$commit_line" | cut -d'|' -f4 | cut -d'@' -f1)
                                            commit=$(echo "$commit_line" | cut -d'|' -f5-)
                                            say "${bold}${category}${normal}: ${purple}${author}${normal} ${repo_name}:${lightblue}${branch_name}${normal} $hash - $commit$(get_url commit $url $hash)"
                                        done
                                    IFS="$OLDIFS"
                                    ;;
                                *new\ branch*)
                                    branch_name=$(echo "$line" | awk '{ print $3 }')
                                    say "${bold}${category}${normal}: ${repo_name}:${lightblue}${branch_name}${normal} - new branch created$(get_url branch $url $branch_name)"
                                    ;;
                                *new\ tag*)
                                    tag_name=$(echo "$line" | awk '{ print $3 }')
                                    say "${bold}${category}${normal}: ${repo_name}:${lightblue}${tag_name}${normal} - new tag created$(get_url tag $url $tag_name)"
                                    ;;
                            esac
                        done <<< "$changes"

                        cd - &>/dev/null
                    fi
                } &

            if [[ "$jobs" -ge "$max_jobs" ]];then
                wait
            fi
        done
    fi
    interval
    sleep "$interval"
done

