#!/bin/bash
# synchronize repos to get the unofficial ones automatically
# set this on a cronjob

export PALUDIS_LOG_DIRECTORY="$HOME"/.paludis-monitor
export CAVE="cave -E :monitor"

cd "$HOME"/git/infra-scripts
git reset --hard HEAD; git pull -vf
$CAVE sync

